#!/bin/bash
# Väljastab tärnid reas vastavalt kasutaja sisestusele kahanevas järjekorras
echo -n "Sisesta vajaminevad read: "
read rida
for (( i = $rida ; i>= 1; i-- ))
	do
		for (( j = 1 ; j<= $rida; j++ ))
		do
		if [ $i -ge $j ]; then
		echo -n "*"
	else
	echo -n " "
	fi
	done
echo ""
done
#skripti lõpp
